---
name: 'Custom: Tests'
on:
  repository_dispatch:
    types: [ dev-deployed ]
jobs:
  tests:
    name: 'Tests'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v6

      - name: 'Run Tests'
        run: |
          echo 'Triggered by "${{ github.event.client_payload.repository }}" repository.'
          echo 'Running tests on the "${{ github.event.client_payload.environment }}" environment.'
